<?php


// drupal_mail('w21_newsletter2go', 'doi', $email, $GLOBALS['language'], $mail_params);

/**
 * Implements hook_init() for testing.
 */
function newsletter2go_init() {
   // dpm(newsletter2go_get_client());
}

function newsletter2go_get_client($key = "", $api_lang = "", $debug = NULL) {
  $library = libraries_load("newsletter2go");

  if ( empty($library['loaded'])) {
      $args = array(
        '%library' => 'Newsletter2Go',
        '!error_message' => $library['error message'],
      );
      drupal_set_message(t("Problem loading %library library: !error_message", $args), 'error', TRUE);
      return FALSE;
  }

  if(empty($key)) {
    $key = variable_get('newsletter2go_key', '');
    if(empty($key)) {
      drupal_set_message(t("In order to use the Newsletter2Go API the variable 'newsletter2go_key' must be set included in settings.php's \$conf array. See newsletter2go module's README.txt for more info."), 'error', TRUE);
      return FALSE;
    }
  }

  if(empty($api_lang)) {
    $lang = variable_get('newsletter2go_api_lang', "de");
  }

  if(empty($debug)) {
    $lang = variable_get('newsletter2go_debug', FALSE);
  }

  return new newsletter2go($key, $lang, $debug);
}

/**
 * Implements hook_requirements()
 */
function newsletter2go_requirements($phase) {
  $requirements = array();
  if ($phase == 'runtime') {
    $t = get_t();
    if ($path = libraries_get_path('newsletter2go')) {
      if (file_exists($path . '/newsletter2go.class.php')) {
        $requirements['newsletter2go'] = array(
          'title' => $t('Newsletter2Go'),
          'value' => $t('newsletter2go.class.php found under !path', array('!path' => $path . '/newsletter2go.class.php')),
          'severity' => REQUIREMENT_OK,
        );
        return $requirements;
      }
    }
    $requirements['newsletter2go'] = array(
      'title' => $t('Newsletter2Go'),
      'value' => $t('newsletter2go.class.php library was not found. !download the library and place in under sites/all/libraries/newsletter2go, so that the library can be found at sites/all/libraries/newsletter2go/newsletter2go.class.php.', array('!download' => l(t('Download'), 'http://www.newsletter2go.de/'))),
      'severity' => REQUIREMENT_ERROR,
    );
  }
  return $requirements;
}

/**
 * Implements hook_libraries_info().
 */
function newsletter2go_libraries_info() {
  $libraries = array();
  $libraries['newsletter2go'] = array(
    'name' => 'newsletter2go',
    'files' => array(
      'php' => array(
        'newsletter2go.class.php',
      ),
    ),
    'version callback' => 'newsletter2go_version_callback',
  );
  return $libraries;
}


function newsletter2go_version_callback() {
  return TRUE;
}
